---
# tasks file for ec2-lb

- name: "Install {{ pkg }}"
  package:
    name: "{{ pkg }}"
    state: present

- name: "Copy {{ pkg }} configuration file"
  template:
    src: haproxy.cfg.j2
    dest: "{{ cfg_path }}"
  notify: 
  - "Restart Service"

- name: "Start {{ service_name }} service"
  service:
    name: "{{ service_name }}"
    state: started
